### PR TITLE
rework example 5 / function call

### PR DESCRIPTION
**Pull request by nkrusch**
@aubertc please review this change.

The analysis of this is infinite (f is infinite). Should we use something that is not infinite?

### CODE REVIEW

**Comment by aubertc** [comment]
I don't think that example being infinite matters a lot.
What matters is that both analyses agree (after projections), and this is the case 

That being said, the example in the paper is `loop X 1 { X 2 = X 2+X 2 };`, and that was translated to `while(X1) { X2 = X2 + X2; }`, but one will be analyzed with the L rule while the other will be analyzed with the W rule.

It may be better to change _the paper_ to use `while` instead of loop (and, in that case, it would just be `while(b)`, but we can in the code replace `b` with `X1` if we wish, indeed).

**Comment by aubertc** [comment]
One last comment: we may want to highlight more clearly in the output of example5_a.c  that
1. Two functions are analyzed,
2. The function call is "skipped".

I know there are many statements that are skipped, but, in this particular case, having the analysis display "_you called a previously analyzed function, this feature is not supported but will be soon_" could be good, what do you think?

**Comment by nkrusch** [comment]
- I used while because that is the only supported repetition statement
- making in not infinite is not a bit deal, if we are mainly interested in the matrix, we get matrix either way
- the references will persist if we use permalink and link to code at a point in time. My concern is links to the website which will break over time
- regarding highlighting more clearly: I will update the examples to add comments to explain this

>  having the analysis display "you called a previously analyzed function, this feature is not supported but will be soon" could be good

If you inspect my change closely, you will see the one example has two functions in one file and in the output you see the analysis for both functions. which is a new feature. I also generated the matching AST, from which I can see it generates some new types of nodes we have not handled previously, e.g. `FuncCall`, so we can certainly add to analysis and handler for this to say if e.g. `FuncCall` is encountered to display this output you suggested.

**Comment by aubertc** [comment]
> which is a new feature.

Yeah, I've noticed that, it's  great that we can now analyze multiple functions in the same file. Now that you've added that `FunCall`, we are actually super close to implementing it :-)

> It may be better to change the paper to use while instead of loop (and, in that case, it would just be while(b), but we can in the code replace b with X1 if we wish, indeed).

I'll take care of that.

**Pull request merged**
