### PR TITLE
changes to eval and choice representation

### PR DESCRIPTION
**Pull request by nkrusch**
Please review this changeset and run it on examples to evaluate its impact.

The evaluation procedure is explained with examples in `choice.py` so I will not repeat it here, but we can discuss it in more.

This approach also changes the representation of choices. Before:

```
[2,2,2,2,0,0,2], [2,2,2,2,0,1,2], [2,2,2,2,0,2,2], [2,2,2,2,1,0,2], [2,2,2,2,1,1,2], 
[2,2,2,2,1,2,2], [2,2,2,2,2,0,2], [2,2,2,2,2,1,2], [2,2,2,2,2,2,2]
```

Equivalent, but now more compact:

```
[[[2], [2], [2], [2], [0, 1, 2], [0, 1, 2], [2]]]
```

Which is read as:  choose a vector (there could be multiple, it is a list of lists), then choose one of the remaining choices at each index; this will give a valid derivation.

This change has some practical implications:

- faster eval+compact representation of choices enables analyzing programs with larger index (more assignments) and also reasonably displaying or writing those results to file
- it enables evaluating programs like long.c, whose index is 13, which is also introduced in this changeset
- it is now possible to evaluate the original dense.c (in tests/test_examples/complex_dense.c) -- it still takes ~1 min to analyze, but the evaluation step is instantaneous
- the analysis phase is now more significant regarding performance
- removes progress bar external dependency

### CODE REVIEW

**Comment by nkrusch** [comment]
I linked issue #52 here because if this PR is merged, the issue is no longer relevant.

**Review by aubertc — APPROVED** [review]
I have been through the code, and don't have any other comment: it is clean, documented, modular and the tests have been updated.
I really don't have anything else to say, that's just perfect.

**Comment by aubertc** [comment]
> I linked issue #52 here because if this PR is merged, the issue is no longer relevant.

Absolutely.

**Comment by aubertc** [comment]
Not sure where is the best place to store this example we started working on, so I'm just posting it here, @nkrusch , for the record. Implementing something of that sort or using it to explain the algorithm could be useful.

example_eval

**Comment by nkrusch** [comment]
Thanks for this picture. I was "just" going to go over it quickly and document it but then I realized I had crossed out the third row, so it should give 4 results (not an issue for correctness, just overly verbose) :

```
[[2],[0],[0,1,2]],
[[2],[0,1],[0,2]],
[[2],[0,2],[0,2]],
[[2],[0,1,2],[0,2]]
```

And what I actually want is:

```
[[2],[0],[0,1,2]],
[[2],[0,1,2],[0,2]]
```

So, clearly need to improve the simplification steps. It has to do with the duplicated delta `(1,2)` in the two longer sequences, but I am having a bit of hard time trying to figure out how to handle it in general case.

Working in reverse[^note]:

```
(0,0)   (0,1)   ((2,1) (1,2))   ((2,0)(1,1)(1,2))  ----(?)---->    (0,0)   (0,1)   (???)   (???) 
```

Then combining element-wise in all possible ways, it should have only the following two remaining, since this is minimal form:

```
(0,0) (1,0) (1,1) (2,1) => [[2],[0],[0,1,2]] 
(0,0) (1,0) (1,2) (1,2) => [[2],[0,1,2],[0,2]]   # same as writing (0,0) (1,0) (1,2)
```

How can I determine these two are redundant:

```
(0,0) (1,0) (2,1) (1,2) => [[2],[0,1],[0,2]] 
(0,0) (1,0) (1,2) (1,1) => [[2],[0,2],[0,2]]
```

In both cases I am pairing a delta from one sequence with the duplicated `(1,2)` pair.  So, since `(0,0) (1,0) (1,2)` by itself is bad, we do not need `(0,0) (1,0) (1,2) (1,1)` and `(0,0) (1,0) (2,1) (1,2)`.

It may also be the case that perhaps the simplification should be done after generating the element-wise combinations; not at the point in time above where I wrote `(?)` earlier. When combining with some duplicated delta, it will generate n-1 distinct deltas, then any other combination that contains the n-1 sequence is automatically bad. I can also see this could apply in a case where some delta is duplicated across more than 2 sequences. Perhaps I should make all combinations and remove the redundant options at that point?

[^note]:  Also: anything with `(2,0)` is automatically bad, since we also have `(0,0)` and `(1,0)` and could ignored _before_ generating all combinations, so the deltas can be simplified to: `(0,0)   (0,1)   ((2,1)(1,2))   ((1,1)(1,2))`; another improvement. I check for it now, but only after generating combinations, which means ~some small number of unnecessary iterations.

**Pull request merged**
